server:
  port: 8080

spring:
  application:
    name: myfinances-back
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/myfinances
  datasource:
    url: jdbc:postgresql://localhost:5432/myfinance_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

app:
  params:
    defaultPassword: "MyFinances@123"
  jwt:
    secret: "myfinances-jwt-session-secret-key"
    expiration-minutes: 3

logging:
  level:
    br.com.infotech.myfinances: DEBUG
